---
title: "Phenols for manuscript"
author: "Zhang Zhenglin"
output:
  pdf_document:
    toc: yes
editor_options:
  markdown:
    wrap: sentence
---

# Necessary libraries

```{r message=FALSE,warning=FALSE}
library(knitr)
library(rlang)
library(ggplot2)
theme_set(theme_bw())
library(emmeans)
library(multcomp)
library(PLS205)
library(lme4)
library(lmerTest)
library(multcompView)
library(car)
library(Rmisc) 
library(dplyr) #https://r4ds.had.co.nz/ (Chapter 3, Chapter 5, look at filter and select)
# https://bookdown.org/ansellbr/WEHI_tidyR_course_book/
library(stringr) 
library(data.table)
library(GGally)
library(formatR)
library(readxl)
library(mgcv)
library(openxlsx)

```

# RES

```{r}
RES <- read_excel("RES_25Jan2024.xlsx", sheet = 1)
RES <- mutate_if(RES, is.character, as.factor)
RES$Year <- as.factor(RES$Year)

str(RES)
```

```{r}
Total_P_RES <- lmer(TotalP ~ Field+(1|Blk), data=RES)
Total_P_means_RES <- emmeans(Total_P_RES, spec ='Field')
Total_P_effects_RES <- contrast(Total_P_means_RES, method = 'pairwise', adjust = "tukey")
anova(Total_P_RES)
cld(Total_P_means_RES)
summary(Total_P_effects_RES)

Total_V_RES <- lmer(TotalV ~ Field+(1|Blk), data=RES)
Total_V_means_RES <- emmeans(Total_V_RES, spec ='Field')
Total_V_effects_RES <- contrast(Total_V_means_RES, method = 'pairwise', adjust = "tukey")
anova(Total_V_RES)
cld(Total_V_means_RES)
summary(Total_V_effects_RES)

Total_C_RES <- lmer(TotalC ~ Field+(1|Blk), data=RES)
Total_C_means_RES <- emmeans(Total_C_RES, spec ='Field')
Total_C_effects_RES <- contrast(Total_C_means_RES, method = 'pairwise', adjust = "tukey")
anova(Total_C_RES)
cld(Total_C_means_RES)
summary(Total_C_effects_RES)

Total_S_RES <- lmer(TotalS ~ Field+(1|Blk), data=RES)
Total_S_means_RES <- emmeans(Total_S_RES, spec ='Field')
Total_S_effects_RES <- contrast(Total_S_means_RES, method = 'pairwise', adjust = "tukey")
anova(Total_S_RES)
cld(Total_S_means_RES)
summary(Total_S_effects_RES)

Total_phenols_RES <- lmer(Total_phenols ~ Field+(1|Blk), data=RES)
Total_phenols_means_RES <- emmeans(Total_phenols_RES, spec ='Field')
Total_phenols_effects_RES <- contrast(Total_phenols_means_RES, method = 'pairwise', adjust = "tukey")
anova(Total_phenols_RES)
cld(Total_phenols_means_RES)
summary(Total_phenols_effects_RES)
```

# Regional Survey 

```{r}
Growers <- read_excel("Regional_survey_25Jan2024.xlsx", sheet = 1)
Growers <- mutate_if(Growers, is.character, as.factor)
Growers$Year <- as.factor(Growers$Year)

str(Growers)
```


```{r}
Total_P_Growers <- lmer(TotalP ~ Field+(1|Site), data=Growers)
Total_P_means_Growers <- emmeans(Total_P_Growers, spec ='Field')
Total_P_effects_Growers <- contrast(Total_P_means_Growers, method = 'pairwise', adjust = "tukey")
anova(Total_P_Growers)
cld(Total_P_means_Growers)
summary(Total_P_effects_Growers)

Total_V_Growers <- lmer(TotalV ~ Field+(1|Site), data=Growers)
Total_V_means_Growers <- emmeans(Total_V_Growers, spec ='Field')
Total_V_effects_Growers <- contrast(Total_V_means_Growers, method = 'pairwise', adjust = "tukey")
anova(Total_V_Growers)
cld(Total_V_means_Growers)
summary(Total_V_effects_Growers)

Total_C_Growers <- lmer(TotalC ~ Field+(1|Site), data=Growers)
Total_C_means_Growers <- emmeans(Total_C_Growers, spec ='Field')
Total_C_effects_Growers <- contrast(Total_C_means_Growers, method = 'pairwise', adjust = "tukey")
anova(Total_C_Growers)
cld(Total_C_means_Growers)
summary(Total_C_effects_Growers)

Total_S_Growers <- lmer(TotalS ~ Field+(1|Site), data=Growers)
Total_S_means_Growers <- emmeans(Total_S_Growers, spec ='Field')
Total_S_effects_Growers <- contrast(Total_S_means_Growers, method = 'pairwise', adjust = "tukey")
anova(Total_S_Growers)
cld(Total_S_means_Growers)
summary(Total_S_effects_Growers)

Total_phenols_Growers <- lmer(Total_phenols ~ Field+(1|Site), data=Growers)
Total_phenols_means_Growers <- emmeans(Total_phenols_Growers, spec ='Field')
Total_phenols_effects_Growers <- contrast(Total_phenols_means_Growers, method = 'pairwise', adjust = "tukey")
anova(Total_phenols_Growers)
cld(Total_phenols_means_Growers)
summary(Total_phenols_effects_Growers)
```

# Import graphing data

```{r}
manuscript_graphing <- read_excel("Phenols_graphing_manuscript_25Jan2024.xlsx", sheet = 1)

RES_graphing <- manuscript_graphing %>% filter(Study == "RES")
str(RES_graphing)

Growers_Graphing <- manuscript_graphing %>% filter(Study == "Grower")
str(Growers_Graphing)
```

# Graphing RES

```{r}
RES_phenols_graph <-
ggplot(RES_graphing, aes(x = Type, y = Phenols_level, fill = Field)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.7) +
  labs(x = "Type", y = "Phenols_level", fill = "Field") +
  scale_fill_manual(values = c("#0072B2","#FFCC66"),labels = c("Continuous rice (CR)", "Fallow rice (FR)"))+
  scale_y_continuous(name=expression("Phenols level (mg 100g"^{-1}*" OC)"), limits = c(0,3), expand = c(0, 0))+
  scale_x_discrete(name="", labels = c("Total phenols", "Cinnamic phenols", "P-hydroxybenzyl phenols", "Syringyl phenols", "Vanillyl phenols"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size= 12))+
  theme(axis.text.y = element_text(size= 12),axis.title = element_text(size=12))+
  theme(legend.text = element_text(size = 12),legend.title = element_text(size = 13))+
    annotate(
  "text",
  x = c(1,2,5),  # X-axis positions for annotations
  y = c(2.1,0.65,0.65),  # Y-axis positions for annotations
  label = "*",
  size = 8,
  vjust = 0  # Adjust vertical position of asterisks
)+
  annotate(
  "text",
  x = c(3),  # X-axis positions for annotations
  y = c(2.8),  # Y-axis positions for annotations
  label = "RES",
  size = 5,
  vjust = 0  
)

RES_phenols_graph

ggsave(RES_phenols_graph, filename = "RES_phenols_graph_22Jan2024.png", height = 15, width = 20, units = "cm", dpi=1000)
```
# Graphing growers' fields

```{r}
Grower_phenols_graph<-
ggplot(Growers_Graphing, aes(x = Type, y = Phenols_level, fill = Field)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.7) +
  labs(x = "Type", y = "Phenols_level", fill = "Field") +
  scale_fill_manual(values = c("#0072B2","#FFCC66"),labels = c("Continuous rice (CR)", "Fallow rice (FR)"))+
  scale_y_continuous(name=expression("Phenols level (mg 100g"^{-1}*" OC)"), limits = c(0,3), expand = c(0, 0))+
  scale_x_discrete(name="", labels = c("Total phenols", "Cinnamic phenols", "P-hydroxybenzyl phenols", "Syringyl phenols", "Vanillyl phenols"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size= 12))+
  theme(axis.text.y = element_text(size= 12),axis.title = element_text(size=12))+
  theme(legend.text = element_text(size = 12),legend.title = element_text(size = 13))+
    annotate(
  "text",
  x = c(1,2,3,4,5),  # X-axis positions for annotations
  y = c(2.4,0.8,0.3,1,0.7),  # Y-axis positions for annotations
  label = "*",
  size = 8,
  vjust = 0  # Adjust vertical position of asterisks
)+
  annotate(
  "text",
  x = c(3),  # X-axis positions for annotations
  y = c(2.8),  # Y-axis positions for annotations
  label = "Regional survey study",
  size = 5,
  vjust = 0  
)

Grower_phenols_graph

ggsave(Grower_phenols_graph, filename = "Growers_phenols_graph_22Jan2024.png", height = 15, width = 20, units = "cm", dpi=1000)
```
