---
title: "Correlation Analysis of Phenols and N availability"
author: "Zhang Zhenglin"
output:
  pdf_document:
    toc: yes
editor_options:
  markdown:
    wrap: sentence
---

# Necessary libraries

```{r message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
theme_set(theme_bw())
library(emmeans)
library(multcomp)
library(PLS205)
library(lme4)
library(lmerTest)
library(multcompView)
library(car)
library(Rmisc) 
library(dplyr) #https://r4ds.had.co.nz/ (Chapter 3, Chapter 5, look at filter and select)
# https://bookdown.org/ansellbr/WEHI_tidyR_course_book/
library(stringr) 
library(data.table)
library(GGally)
library(formatR)
library(readxl)
library(mgcv)
library(writexl)
```

# Data Organisation

```{r}
preplant <- read_excel("Cor_Base.xlsx", sheet = 1)
str(preplant)

topdress <- read_excel("Cor_Base.xlsx", sheet = 2)
str(topdress)

#cor_data_preplant <- preplant%>%select(-Field,-Blk_Site,-Blk,-Year)
#cor_data_topdress <- topdress%>%select(-Field,-Blk_Site,-Blk,-Year)

cor_data_preplant <- preplant%>%select(-Blk_Site,-Blk,-Year)
cor_data_topdress <- topdress%>%select(-Blk_Site,-Blk,-Year)
```

# Correlation matrix 

```{r}
all_preplant_cor_matrix <-ggpairs(cor_data_preplant %>% select(-Field, -yield_Mgha), 
                                  upper = list(continuous = wrap("cor", size = 5.5))
                                  )+
                          ggtitle("(a) Preplant") +
                          theme(plot.title = element_text(size = 30, face = "bold"))


all_topdress_cor_matrix <-ggpairs(cor_data_topdress %>% select(-Field, -yield_Mgha), 
                                  upper = list(continuous = wrap("cor", size = 5.5))
                                  )+
                          ggtitle("(b) Topdress") +
                          theme(plot.title = element_text(size = 30, face = "bold"))
                        

ggsave(all_preplant_cor_matrix, filename = "all_preplant.png", height = 34, width = 33, units = "cm", dpi = 400)
ggsave(all_topdress_cor_matrix, filename = "all_topdress.png", height = 34, width = 33, units = "cm", dpi = 400)
```


```{r}
citation("GGally")
```
