---
title: "FNR 15N"
author: "Zhang Zhenglin"
output:
  pdf_document:
    toc: yes
  html_notebook:
    toc: yes
    toc_float: yes
editor_options:
  markdown:
    wrap: sentence
---

# Necessary libraries

```{r message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
theme_set(theme_bw())
library(emmeans)
library(multcomp)
library(PLS205)
library(lme4)
library(lmerTest)
library(multcompView)
library(car)
library(Rmisc) 
library(dplyr) #https://r4ds.had.co.nz/ (Chapter 3, Chapter 5, look at filter and select)
# https://bookdown.org/ansellbr/WEHI_tidyR_course_book/
library(stringr) 
library(data.table)
library(GGally)
library(formatR)
library(readxl)
library(mgcv)

```

# Data Organisation

## Read from excel

```{r}
FNR <- read_excel("soils_15N_maturity.xlsx", sheet = 1)
str(FNR)
```

## Clean up variables

```{r}
FNR <- mutate_if(FNR, is.character, as.factor)
FNR$Blk <- as.factor(FNR$Blk)
FNR$Year <- as.factor(FNR$Year)

str(FNR)
```

## Sub dataset for "preplant" and "topdress"

```{r}
preplant <- FNR %>% filter(Topdress == "N")
str(preplant)

topdress <- FNR %>% filter(Topdress == "Y")
str(topdress)
```

# Preplant FNR

## Continuous Rice

```{r}
preplant_CR <- preplant %>% filter(Field == "CR")
mean(preplant_CR$crop_recovery_fert_N_percent)

mean(preplant_CR$soil_recovery_fert_N_percent)

mean(preplant_CR$total_fertN_recovery_percent)
```

## Fallow Rice

```{r}
preplant_RF <- preplant %>% filter(Field == "RF")
mean(preplant_RF$crop_recovery_fert_N_percent)

mean(preplant_RF$soil_recovery_fert_N_percent)

mean(preplant_RF$total_fertN_recovery_percent)
```

## Testing for preplant

```{r}
#total FNR
preplant_total_model <- lmer(total_fertN_recovery_percent~Field*Year+(1|Blk), data = preplant)

anova(preplant_total_model)

preplant_total_means <- emmeans(preplant_total_model, spec ='Field')
preplant_total_effects <- contrast(preplant_total_means, method = 'pairwise', adjust = "tukey")
cld(preplant_total_means)
summary(preplant_total_effects)

#crop FNR
preplant_crop_model <- lmer(crop_recovery_fert_N_percent~Field*Year+(1|Blk), data = preplant)

anova(preplant_crop_model)

preplant_crop_means <- emmeans(preplant_crop_model, spec ='Field')
preplant_crop_effects <- contrast(preplant_crop_means, method = 'pairwise', adjust = "tukey")
cld(preplant_crop_means)
summary(preplant_crop_effects)

#soil FNR
preplant_soil_model <- lmer(soil_recovery_fert_N_percent~Field*Year+(1|Blk), data = preplant)

anova(preplant_soil_model)

preplant_soil_means <- emmeans(preplant_soil_model, spec ='Field')
preplant_soil_effects <- contrast(preplant_soil_means, method = 'pairwise', adjust = "tukey")
cld(preplant_soil_means)
summary(preplant_soil_effects)
```
# Topdress FNR

## Continuous Rice

```{r}
topdress_CR <- topdress %>% filter(Field == "CR")
mean(topdress_CR$crop_recovery_fert_N_percent)

mean(topdress_CR$soil_recovery_fert_N_percent)

mean(topdress_CR$total_fertN_recovery_percent)
```

## Fallow Rice

```{r}
topdress_RF <- topdress %>% filter(Field == "RF")
mean(topdress_RF$crop_recovery_fert_N_percent)

mean(topdress_RF$soil_recovery_fert_N_percent)

mean(topdress_RF$total_fertN_recovery_percent)
```

## Testing for topdress


```{r}
#total FNR
topdress_total_model <- lmer(total_fertN_recovery_percent~Field*Year+(1|Blk), data = topdress)

anova(topdress_total_model)

topdress_total_means <- emmeans(topdress_total_model, spec ='Field')
topdress_total_effects <- contrast(topdress_total_means, method = 'pairwise', adjust = "tukey")
cld(topdress_total_means)
summary(topdress_total_effects)

#crop FNR
topdress_crop_model <- lmer(crop_recovery_fert_N_percent~Field*Year+(1|Blk), data = topdress)

anova(topdress_crop_model)

topdress_crop_means <- emmeans(topdress_crop_model, spec ='Field')
topdress_crop_effects <- contrast(topdress_crop_means, method = 'pairwise', adjust = "tukey")
cld(topdress_crop_means)
summary(topdress_crop_effects)

#soil FNR
topdress_soil_model <- lmer(soil_recovery_fert_N_percent~Field*Year+(1|Blk), data = topdress)

anova(topdress_soil_model)

topdress_soil_means <- emmeans(topdress_soil_model, spec ='Field')
topdress_soil_effects <- contrast(topdress_soil_means, method = 'pairwise', adjust = "tukey")
cld(topdress_soil_means)
summary(topdress_soil_effects)
```
